package edu.sharif.ce.apyugioh.model;

public enum Trigger {
    STANDBY,
    DRAW,
    SET,
    BEFORE_SUMMON,
    AFTER_SUMMON,
    AFTER_MONSTER_KNOCK_OUT,
    BEFORE_FLIP_SUMMON,
    AFTER_FLIP_SUMMON,
    AFTER_TRIBUTE_SUMMON,
    AFTER_NORMAL_SUMMON,
    BEFORE_TRIBUTE_SUMMON,
    BEFORE_ATTACK,
    AFTER_ATTACK,
    AFTER_SPECIAL_SUMMON,
    USER,
    BEFORE_ACTIVE_SPELL,
    AFTER_ACTIVE_SPELL,
    BEFORE_ACTIVE_TRAP,
    AFTER_ACTIVE_TRAP,
    ALWAYS,
    MAIN;
}
