package edu.sharif.ce.apyugioh.model;

public enum MonsterType {
    AQUA, BEAST, BEAST_WARRIOR, CREATOR_GOD, CYBERSE, DINOSAUR, DIVINE_BEAST, DRAGON, FAIRY, FIEND, FISH, INSECT,
    MACHINE, PLANT, PSYCHIC, PYRO, REPTILE, ROCK, SEA_SERPENT, SPELLCASTER, THUNDER, WARRIOR, WINGED_BEAST, WYRM, ZOMBIE
}
